In [18]:
import random
import numpy as np

In [258]:
my_vector = np.array(random.sample(range(0, 10), 10))

In [259]:
my_vector

array([1, 8, 4, 7, 5, 0, 9, 2, 6, 3])

In [ ]:
for i in range(len(my_vector)):
    for _ in (my_vector >= my_vector[i]) == bool(False):
        my_vector = np.hstack((my_vector[my_vector < my_vector[i]],my_vector[my_vector >= my_vector[i]]))

In [172]:
count = 0
for i in range(len(my_vector)):
    for _ in (my_vector >= my_vector[i]) == bool(False):
        my_vector = np.hstack((my_vector[my_vector > my_vector[i]],my_vector[my_vector <= my_vector[i]]))


In [156]:
for i in range(len(my_vector)):
    for j in range(1, len(my_vector)):
        if my_vector[i] > my_vector[j]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [198]:
for i in range(len(my_vector)-1):
    if my_vector[i]>my_vector[i+1]:
        my_vector[i],my_vector[i+1] = my_vector[i+1],my_vector[i]
        i += 1

In [262]:
for i in range(len(my_vector)-1):
    for j in range(i+1, len(my_vector)):
        if my_vector[i] > my_vector[j]:
            my_vector[i],my_vector[j] = my_vector[j],my_vector[i]
            

In [263]:
my_vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [261]:
my_vector

array([1, 8, 4, 7, 5, 0, 9, 2, 6, 3])